### ISSUE TITLE
Install Tips.

### ISSUE THREAD

**Issue by mzch** [Gigamick/burnernote#10]
1. Create database (on your favorite DBMS e.g. MySQL/MariaDB/PostgreSQL/SQLite3)
2. clone this repository.
3. `cp .env.example .env`
4. Edit `.env`
5. `composer install --no-dev`
6. `php artisan key:generate`
7. `php artisan migrate`
8. `php artisan storage:link`
9. `npm install`
10. `npm run production`
11. Point web server to `repository path/public`

**Comment by Gigamick** [comment]
Thanks for this. Is your intention to have this added to the readme?
