### ISSUE TITLE
Update to work with current PHP 8.x version

### ISSUE THREAD

**Issue by elyograg** [Gigamick/burnernote#11]
Today, PHP 7.4 reached end of life status.  Active support ceased a year ago, now they won't even fix security issues.

But I have to have a VM running Ubuntu 20.04 to host my burnernote website because I could not make this package work in Ubuntu 22.04.  The newer Ubuntu includes PHP 8.1, which has been out for a full year.  The 8.0 version was released two years ago.  There are a number of other PHP applications I have that did not  support PHP 8.x as of a few months ago, but in those cases I was able to figure out how to modify the code to get it working.  I am not a PHP developer, and don't even play one on TV.  I do have experience in other programming languages.

**Comment by Gigamick** [comment]
I'll have a look at doing this soon and cheers for using BurnerNote 🤘

**Comment by maffblaster** [comment]
I've got a second vote for this. I'd like to stand up an instance, but rocking PHP 8.2.x presently. We still have PHP 7.4.x available in our main software repository, but it's a little challenging to try to run both at the same time.
