### ISSUE TITLE
XSS  issue

### ISSUE THREAD

**Issue by AntonJoha** [Gigamick/burnernote#2]
The site is vulnerable to a XSS attack. 

This can be tested by writing: 

`<script>alert(1)</script>`

As the given input

I'm not that experienced with php but running the message through something like [htmlspecialchars](https://www.php.net/manual/en/function.htmlspecialchars.php) (if you already don't) is strongly recommended

**Comment by Gigamick** [comment]
Great input, thank you. I'll do this.

**Comment by Gigamick** [comment]
@AntonJoha This has been resolved. Thanks for raising it!
