### ISSUE TITLE
"The note you're trying to access has expired" without password

### ISSUE THREAD

**Issue by sachinkumarsingh092** [Gigamick/burnernote#3]
I get this message every time while trying to share notes with others when we haven't password protected it. 
Works fine when a password is given.
Neither of us nor others opens the note beforehand.

**Comment by Gigamick** [comment]
Interesting. Thanks for raising. How are you sharing the links?

**Comment by sachinkumarsingh092** [comment]
Via private messaging (WhatsApp).

**Comment by sherlockdoyle** [comment]
WhatsApp tries to get a preview for the link, which deletes the message.

**Comment by Gigamick** [comment]
@sachinkumarsingh092 yes as has been stated it looks like some services try to preview the link which makes it self destruct. I am trying to solve this problem now.

Thankyou for raising! Feedback very appreciated!

**Comment by Gigamick** [comment]
@sherlockdoyle @sachinkumarsingh092 This issue is now resolved.

Thanks for drawing my attention to it :-)
