### ISSUE TITLE
Empty Note Allowed!!

### ISSUE THREAD

**Issue by Siddhant-K-code** [Gigamick/burnernote#4]
I am able to create an Empty Note but, even after setting a password, I am redirecting to this.

![image](https://user-images.githubusercontent.com/55068936/144217430-df64cc3a-3585-4cec-bf6c-fa364c0eb011.png)

I think we should not allow users to create an Empty Note (it is just an unnecessary computation)!

**Comment by Gigamick** [comment]
Resolved! Thank you for the feedback!

@Siddhant-K-code
