### ISSUE TITLE
Some basic documentation

### ISSUE THREAD

**Issue by elyograg** [Gigamick/burnernote#5]
There seems to be NO documentation about how to install this.  I finally figured out where to put an app key, and where to configure the app to talk to my database ... but I can't find any instructions for initializing the database with the required structure.  At this point, the main page for the app loads, but I get a 500 error when I try to create a note, and despite enabling the display and logging of errors in PHP, I see no details about what happened.

**Comment by elyograg** [comment]
I figured out how to get the DB created.  I had run "composer update" but not "composer install".  The latter builds the database.  Now I get a 500 error even when loading the main page, whereas before I got it when trying to create a note.

**Comment by elyograg** [comment]
I have it working now.  Permissions in the storage directory was the last hurdle.

**Comment by elyograg** [comment]
While it doesn't throw any errors, the link for a note is missing everything before the /v/ ... and I cannot figure out how to get it to use my URL.  I put it in config/app.php but it seems to be ignoring that.  So many things use environment variables, but there is no info on how to set environment variables.

**Comment by elyograg** [comment]
I'm going to attempt some barebones documentation.

Pick a system running a 7.x release of PHP.  If you're going to use mysql, then on the
DB server, create an empty database.  Create a user, give it "all privileges" on that database.

Clone the git repo or extract the software archive to a directory accessible to your web install.
I chose /var/www to clone the git repo, so I ended up with `/var/www/burnernote` as the install location.
At this point you can either point your web server at the public subdirectory, or you can
symlink burnernote/public to a directory to use in the webserver.  I chose the latter route:

`sudo ln -s burnernote/public /var/www/secrets.domain.tld`

Edit config/database.php so the DB type you're using has the right access info.

In your webserver, create a configuration for the website.
Below is a redacted version of what I have as my Apache virtualhost.
The really important bits here are the AllowOverride and SetEnv options.
The AllowOverride list I have here is probably more than is necessary.  Some
of it was put there while trying to get other self-destructing note apps working.
It is listening on port 81, because I have haproxy listening on 443 and handling the TLS.

```
<VirtualHost *:81>
        ServerName secrets.domain.tld
        ServerAdmin webmaster@localhost
        UseCanonicalName On
        #LogLevel debug

        SetEnv APP_URL "https://secrets.domain.tld"
        SetEnv APP_DEBUG "false"
        SetEnv APP_NAME "secrets.domain.tld"
        SetEnv APP_ENV "production"
        SetEnv APP_KEY "<32 character hex number redacted>"
        SetEnv DB_CONNECTION "mysql"

        DocumentRoot /var/www/secrets.domain.tld
        <Directory /var/www/secrets.domain.tld/>
                Options -Indexes +FollowSymLinks
                AllowOverride FileInfo AuthConfig Limit Indexes Options=All,MultiViews
                Order allow,deny
                Allow from all
        </Directory>

        ErrorLog /var/log/apache2/domains/secrets.domain.tld/error.log
        CustomLog /var/log/apache2/domains/secrets.domain.tld/access.log combined
</VirtualHost>
```

Change ownership on the files in the extracted directory, and then give the web software's user write access to everything in the storage subdirectory.  I also like to remove world-readable permissions from the configuration.  One way:

`sudo chown -R elyograg:www-data /var/www/burnernote`
`sudo chmod o-rwx -R /var/www/burnernote/config`
`sudo chmod g+w -R /var/www/burnernote/storage`

Now you can do the steps that download required software and create the database.  The install will drop the database and then re-create it.  Make sure that PHP composer is installed, and then as the user that owns the files:

`cd /var/www/burnernote`
`composer update`
`composer install`

BTW, one thing I really like about burnernote is that when you view a note, there's an extra step of clicking on a button before the note is destroyed.  This makes it so you can send encrypted notes via systems that pre-load the URL contents, like facebook messenger.  The system I used to have would destroy the note as soon as facebook accessed it, so the recipient never got the note.

**Comment by Gigamick** [comment]
> While it doesn't throw any errors, the link for a note is missing everything before the /v/ ... and I cannot figure out how to get it to use my URL. I put it in config/app.php but it seems to be ignoring that. So many things use environment variables, but there is no info on how to set environment variables.

Sorry you need an env variable 

```
APP_URL="whatever"
```

Apologies for the lack of documentation but in all seriousness I never thought anyone would use this lol.

I'm pleasantly surprised that people are.
