### ISSUE TITLE
empty model?

### ISSUE THREAD

**Issue by michabbb** [Gigamick/burnernote#6]
pardon, am i missing something here ? 😏 

https://github.com/Gigamick/burnernote/blob/aba104c102bd0a70f2a26d34d9daae8a324cc2ad/app/Models/Note.php#L8

**Comment by Gigamick** [comment]
Sorry you'll need to be less facetious lol. What are you getting at?

**Comment by michabbb** [comment]
your model looks very empty, no fillable, for example...

**Comment by Gigamick** [comment]
Ahhh yes I see. I don't do any mass assignments anywhere so I've never needed that. 

I'll add one though. Just because.

**Comment by michabbb** [comment]
nevermind, to be honest, never saw a total empty model in a project, that´s why I was a little bit confused 😏

**Comment by Gigamick** [comment]
> nevermind, to be honest, never saw a total empty model in a project, that´s why I was a little bit confused 😏

No worries, I added an empty fillable just incase it was a security concern for anyone looking to do a dodgy mass assignment. 

However it's a pretty simple app (by design) so an empty model doesn't worry me too much.

That being said, I did implement your change request 🤓
